### ISSUE TITLE
push latest release to supermarket

### ISSUE THREAD

**Issue by mburns** [realityforge/chef-kibana#117]
Release `v0.2.2` to Supermarket and/or add [me](https://supermarket.chef.io/users/burnsie) as a contributor so that I can push to the Supermarket.

**Comment by drenalin23** [comment]
@realityforge Can you add @mburns as a collaborator in the supermarket?  It only lets the owner in the public supermarket do that.

**Comment by realityforge** [comment]
@mburns Added as a collaborator. Kick me if you need anything more!

**Comment by drenalin23** [comment]
Thanks!
