### ISSUE TITLE
Cookbook file recipes/kibana2.rb has a ruby syntax error

### ISSUE THREAD

**Issue by felika** [realityforge/chef-kibana#28]
Below is Detail log

Environment: chef-dk v.0.2.2, berkshelf v.3.1.5

E, [2014-09-25T02:20:59.325760 #1652] ERROR -- : Cookbook file recipes/kibana2.rb has a ruby syntax error:
E, [2014-09-25T02:20:59.325860 #1652] ERROR -- : /home/ubuntu/.berkshelf/cookbooks/kibana-0.1.8/recipes/kibana2.rb:44: syntax error, unexpected ':', expecting kEND
E, [2014-09-25T02:20:59.325910 #1652] ERROR -- :   supports start: true, restart: true, stop: true, status: true
E, [2014-09-25T02:20:59.325940 #1652] ERROR -- :                  ^
E, [2014-09-25T02:20:59.325961 #1652] ERROR -- : /home/ubuntu/.berkshelf/cookbooks/kibana-0.1.8/recipes/kibana2.rb:44: Can't assign to true
E, [2014-09-25T02:20:59.325994 #1652] ERROR -- :   supports start: true, restart: true, stop: true, status: true
E, [2014-09-25T02:20:59.329957 #1652] ERROR -- :                        ^
E, [2014-09-25T02:20:59.329983 #1652] ERROR -- : /home/ubuntu/.berkshelf/cookbooks/kibana-0.1.8/recipes/kibana2.rb:44: syntax error, unexpected ':', expecting '='
E, [2014-09-25T02:20:59.330004 #1652] ERROR -- :   supports start: true, restart: true, stop: true, status: true
E, [2014-09-25T02:20:59.330024 #1652] ERROR -- :                                 ^
E, [2014-09-25T02:20:59.330045 #1652] ERROR -- : /home/ubuntu/.berkshelf/cookbooks/kibana-0.1.8/recipes/kibana2.rb:44: Can't assign to true
E, [2014-09-25T02:20:59.330070 #1652] ERROR -- :   supports start: true, restart: true, stop: true, status: true
E, [2014-09-25T02:20:59.330090 #1652] ERROR -- :                                       ^
E, [2014-09-25T02:20:59.330112 #1652] ERROR -- : /home/ubuntu/.berkshelf/cookbooks/kibana-0.1.8/recipes/kibana2.rb:44: syntax error, unexpected ':', expecting '='
E, [2014-09-25T02:20:59.330133 #1652] ERROR -- :   supports start: true, restart: true, stop: true, status: true
E, [2014-09-25T02:20:59.330156 #1652] ERROR -- :                                             ^
E, [2014-09-25T02:20:59.330176 #1652] ERROR -- : /home/ubuntu/.berkshelf/cookbooks/kibana-0.1.8/recipes/kibana2.rb:44: Can't assign to true
E, [2014-09-25T02:20:59.330198 #1652] ERROR -- :   supports start: true, restart: true, stop: true, status: true
E, [2014-09-25T02:20:59.330218 #1652] ERROR -- :                                                   ^
E, [2014-09-25T02:20:59.330237 #1652] ERROR -- : /home/ubuntu/.berkshelf/cookbooks/kibana-0.1.8/recipes/kibana2.rb:44: syntax error, unexpected ':', expecting '='
E, [2014-09-25T02:20:59.330259 #1652] ERROR -- :   supports start: true, restart: true, stop: true, status: true
E, [2014-09-25T02:20:59.330278 #1652] ERROR -- :                                                           ^
E, [2014-09-25T02:20:59.333194 #1652] ERROR -- : Ridley::Errors::CookbookSyntaxError: Invalid ruby files in cookbook: kibana (0.1.8).
E, [2014-09-25T02:20:59.333439 #1652] ERROR -- : /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.0.0/lib/ridley/chef/cookbook.rb:198:in `validate'

**Comment by drenalin23** [comment]
Cookbook no longer supports Kibana2 and this is a very old ticket.  Closing.
