### ISSUE TITLE
configuration error:  couldn't perform authentication. AuthType not set

### ISSUE THREAD

**Issue by fortran01** [realityforge/chef-kibana#31]
https://github.com/realityforge/chef-kibana/blob/9285f4806b50da71fa2d3850f807f3a9ce5a0ed3/templates/default/vhost3.conf.erb#L31 fails in Centos 6 if basic_auth is off.

Most probably because of http://stackoverflow.com/questions/21265191/apache-authtype-not-set-500-error

**Comment by cyberflow** [comment]
What version of Apache you use?

**Comment by drenalin23** [comment]
Closing for now as not sure we need to support special case for Apache 2.2.
