### ISSUE TITLE
document root incorrect when using nginx and install from release

### ISSUE THREAD

**Issue by dpippenger** [realityforge/chef-kibana#41]
When using install from release on kibana 3.1.2 the document root should be /opt/kibana/current. But the nginx.rb hard codes appending 'current' and 'src' to the document root. Since kibana upstream seems to be somewhat inconsistent with the structure of the git repo and released package contents it may make the most sense for the document root to be a configurable value.

**Comment by mpycio** [comment]
Just came across same issue, had to update nginx config file and remove src subfolder from path.

**Comment by TinaTina** [comment]
:+1:

**Comment by odolbeau** [comment]
:+1:

**Comment by odolbeau** [comment]
Can you release a new version to have this bug corrected please?

**Comment by cyberflow** [comment]
new version 0.1.10 was release.
