### ISSUE TITLE
nginx "default" prevents forwarding to kibana4 port

### ISSUE THREAD

**Issue by monkeywidget** [realityforge/chef-kibana#50]
Observed behavior: kibana4 is not being served from port 80, even after running recipe kibana::nginx

Analysis:
- kibana is listening at port 5601
- The default install of nginx includes the file "/etc/nginx/sites-enabled/default", which is a link to "/etc/nginx/sites-available/default"
- this file specifies configuration to port 80
- however we want the file "/etc/nginx/sites-available/kibana" to specify forwarding port 80 to 5601

To fix:
- remove link "/etc/nginx/sites-enabled/default"

**Comment by vkhatri** [comment]
@monkeywidget you can disable nginx default site by `default['nginx']['default_site_enabled']   = false` in your role/wrapper cookbook.

**Comment by monkeywidget** [comment]
ooh!  Thanks, I'll try that.

**Comment by monkeywidget** [comment]
That did the trick.  Thanks @vkhatri  !
