### ISSUE TITLE
Proxy templates have hardcoded attributes

### ISSUE THREAD

**Issue by atward** [realityforge/chef-kibana#57]
Both the nginx and apache templates have hardcoded host (127.0.0.1) and/or port (9200) for the elasticsearch proxy functionality. These should refer to node['kibana']['elasticsearch']['port'] and node['kibana']['elasticsearch']['hosts']

**Comment by realityforge** [comment]
Thanks for the heads up. This is something that should be fixed, unfortunately I don't quite have the cycles at the moment. Patches gladly accepted ;)

**Comment by realityforge** [comment]
Fixed by #65
