### ISSUE TITLE
kibana4 in 0.1.8

### ISSUE THREAD

**Issue by a-zen** [realityforge/chef-kibana#58]
Hi,

is there are reason why the kibana4 recipe is not included in version 0.1.8?
Can you release a newer version with the kibana4 recipe included?

--
regards
 alex

**Comment by barisik** [comment]
Same problem

**Comment by realityforge** [comment]
The only reason is that I haven't around to releasing it.

I am looking for someone to help maintain and happy to give you access to this repo and the chef.io account if you are interested

**Comment by barisik** [comment]
Yes, I will be happy to help you with this.
________________________________

**Comment by realityforge** [comment]
Great - I had added you as a collaborator. If you send me the name of your
chef.io account I can add you to the project there so you can perform
releases

On Tue, Oct 27, 2015 at 4:21 PM, barisik <notifications@github.com> wrote:

> Yes, I will be happy to help you with this.
> ________________________________
> From: Peter Donald<mailto:notifications@github.com>
> Sent: ‎10/‎27/‎2015 4:15 AM
> To: realityforge/chef-kibana<mailto:chef-kibana@noreply.github.com>
> Cc: barisik<mailto:ihor.bilovus@outlook.com>
> Subject: Re: [chef-kibana] kibana4 in 0.1.8 (#58)
>
> The only reason is that I haven't around to releasing it.
>
> I am looking for someone to help maintain and happy to give you access to
> this repo and the chef.io account if you are interested
>
> ---
> Reply to this email directly or view it on GitHub:
>
> https://github.com/realityforge/chef-kibana/issues/58#issuecomment-151344669
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/realityforge/chef-kibana/issues/58#issuecomment-151378191>
> .
>



-- 
Cheers,

Peter Donald

**Comment by barisik** [comment]
Hey.. My chef.io account name is - barisik

**Comment by realityforge** [comment]
And @barisik you are added as a collaborator for the cookbook on chef.io - feel free to go to town.

If you need anything from me - feel free to ask

**Comment by barisik** [comment]
@realityforge Thank you.

**Comment by drenalin23** [comment]
Closing as we have added @cyberflow @barisik and @drenalin23 to the collaborators team and it looks like version 0.1.10 is released in the supermarket.
