### ISSUE TITLE
Kibana cookbook is outdated in chef supermarket

### ISSUE THREAD

**Issue by devsathish** [realityforge/chef-kibana#60]
I'm trying to install kibana cookbook from supermarket. Looks like its outdated and doesn't support Kibana 4.
Can you please upload the latest version to supermarket?

https://github.com/realityforge/chef-kibana
https://supermarket.chef.io/cookbooks/kibana

**Comment by cyberflow** [comment]
cookbook version 0.1.10 was upload to supermarket
