### ISSUE TITLE
owner not correct for file tree

### ISSUE THREAD

**Issue by tewingflite** [realityforge/chef-kibana#63]
When installing kibana4.4.2 with this cookbook the file permissions on /opt/kibana/current/* are not set correctly.  The release tarball is extracted after the recursive directory permissions are set.  This can be fixed by adding "user" and "group" properties to the ark provider within recipes/kibana4.rb like this:

     version node['kibana']['kibana4_version']
     checksum node['kibana']['kibana4_checksum']
     path node['kibana']['base_dir']
+    owner node['kibana']['user']
+    group node['kibana']['group']
     home_dir File.join(node['kibana']['base_dir'], 'current')
   end
   config_path = 'current/config/kibana.yml'

Thank you,
-Terry

**Comment by cyberflow** [comment]
it should be fixed #61
