### ISSUE TITLE
kibana4 error

### ISSUE THREAD

**Issue by sailajajavvaji** [realityforge/chef-kibana#64]
Facing this error with kibana4 recipe _service.rb

Recipe: kibana::_service

service[kibana] action start

** ** Error executing action start on resource 'service[kibana]'****

Mixlib::ShellOut::ShellCommandFailed

Expected process to exit with [0], but received '1'
---- Begin output of /sbin/start kibana ----
STDOUT: 
STDERR: start: Job failed to start
---- End output of /sbin/start kibana ----
Ran /sbin/start kibana returned 1

Resource Declaration:

In /var/chef/cache/cookbooks/kibana/recipes/_service.rb

3: service 'kibana' do
4: provider Chef::Provider::Service::Upstart
5: supports start: true, restart: true, stop: true, status: true
6: action :start
7: end
8:

Compiled Resource:

Declared in /var/chef/cache/cookbooks/kibana/recipes/_service.rb:3:in `from_file'

service("kibana") do
provider Chef::Provider::Service::Upstart
action [:start]
supports {:start=>true, :restart=>true, :stop=>true, :status=>true}
retries 0
retry_delay 2
default_guard_interpreter :default
service_name "kibana"
pattern "kibana"
declared_type :service
cookbook_name "kibana"
recipe_name "_service"
end

Running handlers:
[2016-04-20T17:46:20+05:30] ERROR: Running exception handlers
Running handlers complete
[2016-04-20T17:46:20+05:30] ERROR: Exception handlers complete
Chef Client failed. 1 resources updated in 08 seconds
[2016-04-20T17:46:20+05:30] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-04-20T17:46:20+05:30] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-04-20T17:46:20+05:30] ERROR: servicekibana had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /sbin/start kibana ----
STDOUT: 
STDERR: start: Job failed to start
---- End output of /sbin/start kibana ----
Ran /sbin/start kibana returned 1

**Comment by cyberflow** [comment]
need more information. what platform? what chef version? what you see in /var/log/upstart/kibana.log? What version of cabin you configured?

**Comment by drenalin23** [comment]
Closing for now as no further input was provided.  We recently updated the _service.rb to include support for more service types which may resolve your issue.
