### ISSUE TITLE
deprecated kibana v2

### ISSUE THREAD

**Issue by cyberflow** [realityforge/chef-kibana#68]
it make sense to continue to support kibana version 2? Because it's greatly complicates the development and maintenance of cookbook and tests.

also ruby 1.9.3

**Comment by realityforge** [comment]
I don't have strong views on that and I can see it would of benefit to drop it to reduce maintenance. If you were given collaborator status to this repository and I gave you the ability to upload chef supermarket, would you be interested in helping to maintain this cookbook?

**Comment by cyberflow** [comment]
@realityforge Yes, it interested for me. My name in chef supermarket is `cyberflow`. Thank you.

**Comment by realityforge** [comment]
Added you as a collaborator both here and on the supermarket site. If you need anything more just message me

**Comment by cyberflow** [comment]
@realityforge Thank you.
