### ISSUE TITLE
_service.rb not compatible with rhel

### ISSUE THREAD

**Issue by chakatz** [realityforge/chef-kibana#70]
The directory '/etc/init/' where this recipe tries to put the kibana.conf does not exist in RHEL/CentOS etc. Services are configured differently in RHEL land.

**Comment by chakatz** [comment]
Chef output on CentOS 7:

Recipe: kibana::_service
  * service[kibana] action nothing (skipped due to action :nothing)
  * template[/etc/init/kibana.conf] action create
    * Parent directory /etc/init does not exist.
    ================================================================================
    Error executing action `create` on resource 'template[/etc/init/kibana.conf]'
    ================================================================================

    Chef::Exceptions::EnclosingDirectoryDoesNotExist
    ------------------------------------------------
    Parent directory /etc/init does not exist.

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/kibana/recipes/_service.rb

      9: template '/etc/init/kibana.conf' do
     10:   cookbook node['kibana']['service']['cookbook']
     11:   source node['kibana']['service']['source']
     12:   variables(
     13:     version: node['kibana']['version'],
     14:     options: '', # TODO
     15:     recent_upstart: (node['platform_family'] != 'rhel')
     16:   )
     17:   notifies :restart, 'service[kibana]', :delayed
     18: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/kibana/recipes/_service.rb:9:in `from_file'

    template("/etc/init/kibana.conf") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      path "/etc/init/kibana.conf"
      backup 5
      atomic_update true
      source "upstart.conf.erb"
      cookbook "kibana"
      variables {:version=>"4", :options=>"", :recent_upstart=>false}
      declared_type :template
      cookbook_name "kibana"
      recipe_name "_service"
    end

**Comment by drenalin23** [comment]
We could add something like this to the cookbook -
https://github.com/edgarmartinez922/script/blob/master/init_kibana

According to the thread here -
https://github.com/elastic/kibana/issues/1595
The folks maintaining kibana aren't going to add a service script back into the packages for CentOS6.

**Comment by drenalin23** [comment]
Another reference for an init script for centos6/rhel6
https://github.com/cjcotton/init-kibana

**Comment by gfediere** [comment]
just made a pull request to patch rhel with systemd (https://github.com/realityforge/chef-kibana/pull/79)

**Comment by drenalin23** [comment]
@chakatz This should be fixed in https://github.com/realityforge/chef-kibana/pull/80.  If you are able to can you test on your end?

**Comment by drenalin23** [comment]
Please re-open this if this doesn't solve the problem this was initially opened for.
