### ISSUE TITLE
apache2 cookbook support needs to be updated

### ISSUE THREAD

**Issue by drenalin23** [realityforge/chef-kibana#81]
We are dependent on the apache2 cookbook for installs with apache.  The supermarket cookbook has deprecated some attributes that we reference as of version 3.1 of their cookbook.  We need to refactor and update to be able to take advantage of the latest version of the cookbook.

**Comment by salsa-dev** [comment]
Hi, that would be great!

node['apache']['listen_ports'] is depricated and fails the first

**Comment by drenalin23** [comment]
@salsa-dev @cyberflow 
I believe this PR should address - https://github.com/realityforge/chef-kibana/pull/82
