### ISSUE TITLE
support Kibana 5.x

### ISSUE THREAD

**Issue by Paul424** [realityforge/chef-kibana#99]
Trying to deploy Kibana 5.x using this cookbook; so far not succesfull...

What would be the best approach? Create a wrapper cookbook? cp + modify the whole? fork/add/PR?

**Comment by drenalin23** [comment]
Hi Paul - There are a couple of us that have worked on the cookbook recently - if you'd like to update and add v5 support that would be great.  Depending on your skillset, there are a couple of issues (like making the kibana an install an LWRP) that might be great if we add v5 support.

**Comment by Paul424** [comment]
For now i simply added the few relevant resources to my own site-cookbook. Configuration is trivial....
I already had some nginx proxy passes in another recipe; i've added one for kibana, so that explains why it is missing here...

Maybe it helps someone:


download_url = node['kibana']['url']
filename = download_url.split('/').last

remote_file "#{Chef::Config[:file_cache_path]}/#{filename}" do
  source download_url
  mode 00644
  action :create
end

if node['platform_family'] == 'debian'
  dpkg_package "#{Chef::Config[:file_cache_path]}/#{filename}" do
    action :install
  end
else
  package "#{Chef::Config[:file_cache_path]}/#{filename}" do
    action :install
  end
end

# Just run it manually when it fails: /usr/share/kibana/bin$ sudo ./kibana-plugin install x-pack
execute 'plugin_x_pack' do
  command './kibana-plugin install x-pack'
  cwd '/usr/share/kibana/bin'
  creates '/usr/share/kibana/plugins/x-pack'
  action :run
end

service 'kibana' do
  supports start: true, restart: true, stop: true, status: true
  action [:enable, :start]
end

template '/etc/kibana/kibana.yml' do
  source 'kibana.yml.erb'
  owner 'kibana'
  group 'kibana'
  mode '0644'
  variables(
    bind:           node['kibana']['interface'],
    port:           node['kibana']['port'],
    es_host:        node.elasticsearch_hosts.first,
    es_port:        node.elasticsearch_port,
    index:          node['kibana']['index'],
    defaultapp:     node['kibana']['defaultapp'],
  )
  notifies :restart, 'service[kibana]'
end

**Comment by cyberflow** [comment]
Current version support 5.x Kibana
